# Form implementation generated from reading ui file 'f:\Github\QuotationCreator\QuoteCreatorQT\secondary_window.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_currencyConversions(object):
    def setupUi(self, currencyConversions):
        currencyConversions.setObjectName("currencyConversions")
        currencyConversions.resize(412, 71)
        self.buttonBox = QtWidgets.QDialogButtonBox(currencyConversions)
        self.buttonBox.setGeometry(QtCore.QRect(110, 40, 181, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(currencyConversions)
        self.label.setGeometry(QtCore.QRect(10, 10, 391, 21))
        self.label.setObjectName("label")

        self.retranslateUi(currencyConversions)
        self.buttonBox.accepted.connect(currencyConversions.accept) # type: ignore
        self.buttonBox.rejected.connect(currencyConversions.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(currencyConversions)

    def retranslateUi(self, currencyConversions):
        _translate = QtCore.QCoreApplication.translate
        currencyConversions.setWindowTitle(_translate("currencyConversions", "Dialog"))
        self.label.setText(_translate("currencyConversions", "Remove Vendor1?"))
