# Form implementation generated from reading ui file 'c:\Users\Gebz\Documents\GitHub\QuotationCreator\QuoteCreatorQT\vendor_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(382, 290)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.new_vendor_button = QtWidgets.QPushButton(self.frame)
        self.new_vendor_button.setObjectName("new_vendor_button")
        self.verticalLayout.addWidget(self.new_vendor_button)
        self.edit_vendor_button = QtWidgets.QPushButton(self.frame)
        self.edit_vendor_button.setObjectName("edit_vendor_button")
        self.verticalLayout.addWidget(self.edit_vendor_button)
        self.delete_vendor_button = QtWidgets.QPushButton(self.frame)
        self.delete_vendor_button.setObjectName("delete_vendor_button")
        self.verticalLayout.addWidget(self.delete_vendor_button)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout.addWidget(self.frame, 0, 3, 1, 1)
        self.cancel_button = QtWidgets.QPushButton(Dialog)
        self.cancel_button.setObjectName("cancel_button")
        self.gridLayout.addWidget(self.cancel_button, 1, 2, 1, 1)
        self.vendor_list = QtWidgets.QListWidget(Dialog)
        self.vendor_list.setObjectName("vendor_list")
        self.gridLayout.addWidget(self.vendor_list, 0, 0, 1, 3)
        self.make_choice_button = QtWidgets.QPushButton(Dialog)
        self.make_choice_button.setObjectName("make_choice_button")
        self.gridLayout.addWidget(self.make_choice_button, 1, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.new_vendor_button.setText(_translate("Dialog", "New"))
        self.edit_vendor_button.setText(_translate("Dialog", "Edit"))
        self.delete_vendor_button.setText(_translate("Dialog", "Delete"))
        self.cancel_button.setText(_translate("Dialog", "Cancel"))
        self.make_choice_button.setText(_translate("Dialog", "Choose"))
